import type { BackendChatItem, ChatRoom } from './types';

export const MOCK_CHAT_DATA: BackendChatItem[] = [
  {
    id: '1',
    title: '줄깅 운동회',
    participantCount: 50,
    lastMessage: '혹시 잊으신 분 있을까봐 안내드립니다.\n내일 집합 시간: 13:00 집합 장소: 뚝섬유...',
    timestamp: '14:06',
    thumbnailUrl: '',
    unreadCount: 1,
    group: 'interest',
  },
  {
    id: '2',
    title: '용기내 챌린지',
    participantCount: 14,
    lastMessage: '오늘도 용기내 챌린지 참여했어용 ~! ㅎㅎ',
    timestamp: '2일전',
    thumbnailUrl: '',
    unreadCount: 23,
    group: 'interest',
  },
  {
    id: '3',
    title: '지구야 에코라이프로 약속할게',
    participantCount: 4,
    lastMessage: '다들 고생많으셨어요~!!!!',
    timestamp: '1달전',
    thumbnailUrl: '',
    unreadCount: 12,
    group: 'recent',
  },
];

export const MOCK_ROOMS: ChatRoom[] = [
  {
    id: '1',
    title: '줄깅 운동회',
    participantCount: 50,
    deadline: '마감일 :  2025.12.10',
    dday: 'D - 1',
    thumbnailUrl: '',
    messages: [
      { id: 'd1', type: 'date', text: '2025.12.09' },
      {
        id: 'm1',
        type: 'message',
        sender: 'other',
        text: '공지를 따로 못봐서요 ㅠ.ㅠ',
        time: '오후 2:00',
        avatar: '',
      },
      {
        id: 'm2',
        type: 'message',
        sender: 'other',
        text: '다람쥐',
        time: '오후 2:00',
        avatar: '',
      },
      {
        id: 'm3',
        type: 'message',
        sender: 'me',
        text: '안녕하세요!',
        time: '오후 2:01',
      },
      {
        id: 'm4',
        type: 'message',
        sender: 'me',
        text: '이따 4시쯤 따로 안내 문자 돌린다고 들었으니 기다려보면 될 것 같아요 !!',
        time: '오후 2:01',
      },
      {
        id: 'm5',
        type: 'message',
        sender: 'other',
        text: '줄닝아시던 공식 사이트 들어가서 확인해보세요! 공고에 여러가지 이야기가 많았어서 거기보면 옷 추천이랑 챙겨오면 좋을 것들이 적혀있어서 확인해보시면 좋을 것 같아요 !!',
        time: '오후 2:02',
        avatar: '',
      },
    ],
  },
  {
    id: '2',
    title: '용기내 챌린지',
    participantCount: 14,
    deadline: '마감일 :  2025.12.05',
    dday: 'D - 4',
    thumbnailUrl: '',
    messages: [],
  },
  {
    id: '3',
    title: '지구야 에코라이프로 약속할게',
    participantCount: 4,
    deadline: '마감일 :  2025.11.15',
    dday: '마감',
    thumbnailUrl: '',
    messages: [],
  },
];
