import type { JobPosting } from './types';

export const MOCK_POSTINGS: JobPosting[] = [
  {
    id: 'g1',
    title: '내 나무 갖기 캠페인',
    company: '서울그린트러스트',
    location: '서울 성동구',
    latitude: 37.5636,
    longitude: 127.0365,
    category: '환경보전',
    thumbnail: '',
    workType: '오프라인',
    deadline: '2025.12.19',
    description: '도시 숲 조성을 위한 내 나무 갖기 캠페인입니다.',
  },
  {
    id: 'g2',
    title: '줍깅 운동회',
    company: '한강줍깅크루',
    location: '서울 강남구',
    latitude: 37.4979,
    longitude: 127.0276,
    category: '환경보전',
    thumbnail: '',
    workType: '오프라인',
    deadline: '2025.12.09',
    description: '조깅하며 쓰레기를 줍는 줍깅(플로깅) 운동회!',
  },
  {
    id: 'g3',
    title: '오늘부터 친환경 부스터 ON',
    company: '환경교육센터',
    location: '서울 광진구',
    latitude: 37.5385,
    longitude: 127.0823,
    category: '지속가능성',
    thumbnail: '',
    workType: '혼합',
    deadline: '2025.12.22',
    description: '6개월간 진행되는 친환경 라이프스타일 교육 프로그램입니다.',
  },
];
